name: Docker Image CI

on:
  push:
    branches:    
    - 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/codyseavey/test-app/web:latest
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/codyseavey/test-app/web:latest
        username: codyseavey
        password: ${{ secrets.GITHUB_PACKAGE_TOKEN }}